import { SheetConfig, StatusOption } from '@/types';

// Manual Case Options
const manualCaseOptions: StatusOption[] = [
  { label: 'Address/Contact no update', value: 'Address/Contact no update', color: '#6b7280' },
  { label: 'B2B Appointment', value: 'B2B Appointment', color: '#22c55e' },
  { label: 'COD Delay', value: 'COD Delay', color: '#06b6d4' },
  { label: 'COD to Prepaid Change', value: 'COD to Prepaid Change', color: '#8b5cf6' },
  { label: 'Delayed Pickup', value: 'Delayed Pickup', color: '#10b981' },
  { label: 'Delayed RTO', value: 'Delayed RTO', color: '#f59e0b' },
  { label: 'Delivery Issue', value: 'Delivery Issue', color: '#f97316' },
  { label: 'EDD Breach', value: 'EDD Breach', color: '#8b5cf6' },
  { label: 'EDD Urgent', value: 'EDD Urgent', color: '#d946ef' },
  { label: 'Fake NDR Remark', value: 'Fake NDR Remark', color: '#ef4444' },
  { label: 'Lost/Damaged', value: 'Lost/Damaged', color: '#8b5cf6' },
  { label: 'Misrouted Shipment', value: 'Misrouted Shipment', color: '#fbbf24' },
  { label: 'POD (proof of delivery)', value: 'POD (proof of delivery)', color: '#ec4899' },
  { label: 'Post-Pickup Dispute', value: 'Post-Pickup Dispute', color: '#10b981' },
  { label: 'Re-Attempt', value: 'Re-Attempt', color: '#14b8a6' },
  { label: 'Reverse delivery issues', value: 'Reverse delivery issues', color: '#22c55e' },
  { label: 'Reverse Pickup', value: 'Reverse Pickup', color: '#84cc16' },
  { label: 'Revoke RTO', value: 'Revoke RTO', color: '#f97167' },
  { label: 'RTO the Shipment', value: 'RTO the Shipment', color: '#14b8a6' },
  { label: 'Self-collection', value: 'Self-collection', color: '#8b5cf6' },
  { label: 'Service Failure', value: 'Service Failure', color: '#eab308' },
  { label: 'Wrong Delivery', value: 'Wrong Delivery', color: '#f43f5e' },
  { label: 'Wrong RTO', value: 'Wrong RTO', color: '#f43f5e' },
];

const manualCaseLSDOptions: StatusOption[] = [
  { label: 'Lost', value: 'Lost', color: '#f59e0b' },
  { label: 'Damage', value: 'Damage', color: '#ef4444' },
  { label: 'Service Failure', value: 'Service Failure', color: '#8b5cf6' },
];

const cnRefundLSDOptions: StatusOption[] = [
  { label: 'Credit Note', value: 'Credit Note', color: '#f59e0b' },
  { label: 'Refund', value: 'Refund', color: '#10b981' },
];

// Manual Ticket Status Options
const manualTicketStatusOptions: StatusOption[] = [
  { label: 'Open', value: 'Open', color: '#f59e0b' },
  { label: 'Close', value: 'Close', color: '#10b981' },
];

// Escalation Sheet Configuration
export const escalationSheetConfig: SheetConfig = {
  id: 'escalations',
  name: 'Kalesh Bhandar',
  icon: 'AlertCircle',
  description: 'Manage shipment escalations and track resolution status',
  views: [
    {
      id: 'open',
      name: 'Open Escalations',
      description: 'View all open escalations that need attention',
      filters: [
        {
          columnId: 'is_closed',
          operator: 'equals',
          value: 0, // 0 means open/not closed
        },
      ],
      isDefault: true,
    },
    {
      id: 'closed',
      name: 'Closed Escalations',
      description: 'View all closed and resolved escalations',
      filters: [
        {
          columnId: 'is_closed',
          operator: 'equals',
          value: 1, // 1 means closed
        },
      ],
      isDefault: false,
    },
  ],
  columns: [
    {
      id: 'shipment_no',
      label: 'Shipment No',
      type: 'number',
      width: 120,
      required: false,
      editable: true,
    },
    {
      id: 'awb_no',
      label: 'AWB No',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'notes',
      label: 'Notes',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'highlights',
      label: 'Highlights',
      type: 'highlights',
      width: 350,
      required: false,
      editable: false,
    },
    {
      id: 'partner_name',
      label: 'Partner Name',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'manual_case',
      label: 'Manual Case',
      type: 'status',
      width: 180,
      required: false,
      editable: true,
      options: manualCaseOptions,
    },
    {
      id: 'entity_name',
      label: 'Entity Name',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'master_partner',
      label: 'Master Partner',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'ops_remarks',
      label: 'OPS Remarks',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'partner_remarks',
      label: 'Partner Remarks',
      type: 'longtext',
      width: 200,
      required: false,
      editable: false,
    },
    {
      id: 'followup_remarks',
      label: 'Followup Remarks',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'created_at',
      label: 'Created At',
      type: 'datetime',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'escalation_id',
      label: 'Escalation ID',
      type: 'number',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'vamashipper',
      label: 'Vamashipper',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'source_of_complaint',
      label: 'Source of Complaint',
      type: 'text',
      width: 180,
      required: false,
      editable: true,
    },
    {
      id: 'auto_ticket_status',
      label: 'Auto Ticket Status',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'manual_ticket_status',
      label: 'Manual Ticket Status',
      type: 'status',
      width: 180,
      required: false,
      editable: true,
      options: manualTicketStatusOptions,
    },
    {
      id: 'updated_at',
      label: 'Updated At',
      type: 'datetime',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'latest_tracking_status',
      label: 'Latest Tracking Status',
      type: 'text',
      width: 180,
      required: false,
      editable: false,
    },
    {
      id: 'consignee_name',
      label: 'Consignee Name',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'consignee_no',
      label: 'Consignee No',
      type: 'phone',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'duplicate_awb',
      label: 'Duplicate AWB',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'email_subject',
      label: 'Email Subject',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'last_modified_by',
      label: 'Last Modified By',
      type: 'user-avatar',
      width: 180,
      required: false,
      editable: false,
    },
    {
      id: 'shipment_booking_date',
      label: 'Booking Date',
      type: 'date',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'seller_name',
      label: 'Seller Name',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'seller_mobile',
      label: 'Seller Mobile',
      type: 'phone',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'entity_id',
      label: 'Entity ID',
      type: 'number',
      width: 100,
      required: false,
      editable: false,
    },
    {
      id: 'ticket_delay',
      label: 'Ticket Delay',
      type: 'number',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'lr_number',
      label: 'LR Number',
      type: 'text',
      width: 120,
      required: false,
      editable: true,
    },
    {
      id: 'closure_datetime',
      label: 'Closure DateTime',
      type: 'datetime',
      width: 180,
      required: false,
      editable: true,
    },
    {
      id: 'partner_comment_ndr',
      label: 'Partner Comment NDR',
      type: 'text',
      width: 180,
      required: false,
      editable: false,
    },
    {
      id: 'edd_partner',
      label: 'EDD Partner',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'reattempt_count',
      label: 'Reattempt Count',
      type: 'number',
      width: 140,
      required: false,
      editable: false,
    },
  ],
  defaultSort: {
    columnId: 'created_at',
    direction: 'desc',
  },
  permissions: {
    admin: {
      canView: true,
      canEdit: true,
      canDelete: true,
      canExport: true,
    },
    editor: {
      canView: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
    },
    viewer: {
      canView: true,
      canEdit: false,
      canDelete: false,
      canExport: false,
    },
  },
};

// LSD Sheet Configuration
export const lsdSheetConfig: SheetConfig = {
  id: 'lsd',
  name: 'Nuksaan Nivaran',
  icon: 'AlertCircle',
  description: 'Lost & Damage / Service Failure tracking and credit note management',
  views: [
    {
      id: 'unpaid',
      name: 'Unpaid View',
      description: 'View all entries without credit note/refund details',
      filters: [],
      isDefault: true,
    },
    {
      id: 'paid',
      name: 'Paid View',
      description: 'View all entries with credit note/refund details',
      filters: [],
      isDefault: false,
    },
  ],
  columns: [
    {
      id: 'vamashipper',
      label: 'Vamashipper',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'entry_month',
      label: 'Entry Month',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'entry_date',
      label: 'Entry Date',
      type: 'date',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'customer_name',
      label: 'Customer Name',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'credit_note_refund',
      label: 'Credit Note / Refund',
      type: 'status',
      width: 180,
      required: false,
      editable: true,
      options: cnRefundLSDOptions,
    },
    {
      id: 'email_id',
      label: 'Email id',
      type: 'text',
      width: 200,
      required: false,
      editable: false,
    },
    {
      id: 'shipment_no',
      label: 'Shipment No.',
      type: 'number',
      width: 120,
      required: false,
      editable: true,
    },
    {
      id: 'awb_no',
      label: 'AWB No.',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'rto_awb_no',
      label: 'RTO AWB No.',
      type: 'text',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'duplicate_entry_count',
      label: 'Duplicate Entry Count',
      type: 'number',
      width: 160,
      required: false,
      editable: false,
    },
    {
      id: 'duplicate_with_last_year',
      label: 'Duplicate with last year',
      type: 'text',
      width: 180,
      required: false,
      editable: false,
    },
    {
      id: 'latest_tracking_status',
      label: 'Latest Tracking Status',
      type: 'text',
      width: 180,
      required: false,
      editable: false,
    },
    {
      id: 'product_value',
      label: 'Product Value',
      type: 'number',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'shipping_cost',
      label: 'Shipping Cost',
      type: 'number',
      width: 120,
      required: false,
      editable: false,
    },
    {
      id: 'supplier_name',
      label: 'Supplier Name',
      type: 'text',
      width: 150,
      required: false,
      editable: false,
    },
    {
      id: 'master_supplier_name',
      label: 'Master Supplier Name',
      type: 'text',
      width: 180,
      required: false,
      editable: false,
    },
    {
      id: 'lost_damage_service_failure',
      label: 'Lost & Damage / Service Failure',
      type: 'text',
      width: 220,
      required: false,
      editable: true,
    },
    {
      id: 'credit_note_amount_to_customer',
      label: 'Credit Note Amount to be given to Customer',
      type: 'number',
      width: 280,
      required: false,
      editable: true,
    },
    {
      id: 'remarks',
      label: 'Remarks',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'finance_update',
      label: 'Finance Update',
      type: 'text',
      width: 150,
      required: false,
      editable: true,
    },
    {
      id: 'partner_wise_liability_amount',
      label: 'Partner wise Liability Amount',
      type: 'number',
      width: 220,
      required: false,
      editable: false,
    },
    {
      id: 'credit_note_no_utr_no',
      label: 'Credit Note No. / UTR No.',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'credit_note_date_refund_date',
      label: 'Credit Note Date / Refund Date',
      type: 'date',
      width: 220,
      required: false,
      editable: true,
    },
    {
      id: 'credit_note_refund_amount',
      label: 'Credit Note / Refund Amount',
      type: 'number',
      width: 220,
      required: false,
      editable: true,
    },
    {
      id: 'ops_name',
      label: 'Ops Name',
      type: 'text',
      width: 120,
      required: false,
      editable: true,
    },
    {
      id: 'investigation_status',
      label: 'Investigation Status',
      type: 'text',
      width: 180,
      required: false,
      editable: true,
    },
    {
      id: 'partner_debit_note_no_utr_no',
      label: 'Partner Debit Note No. / UTR No.',
      type: 'text',
      width: 250,
      required: false,
      editable: true,
    },
    {
      id: 'partner_debit_note_date_refund_date',
      label: 'Partner Debit Note Date / Refund Date',
      type: 'date',
      width: 280,
      required: false,
      editable: true,
    },
    {
      id: 'partner_debit_note_amount_refund_amount',
      label: 'Partner Debit Note Amount / Refund Amount',
      type: 'number',
      width: 300,
      required: false,
      editable: true,
    },
    {
      id: 'operations_remarks',
      label: 'Operations Remarks',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'partners_email_subject',
      label: 'Partners Email Subject',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'email_link_of_partner',
      label: 'Email Link of Partner',
      type: 'text',
      width: 200,
      required: false,
      editable: true,
    },
    {
      id: 'partners_email_subject_for_cn_followup',
      label: 'Partners Email Subject FOR CN Followup',
      type: 'text',
      width: 280,
      required: false,
      editable: true,
    },
    {
      id: 'email_link_of_partner_for_cn',
      label: 'Email Link of Partner For CN',
      type: 'text',
      width: 220,
      required: false,
      editable: true,
    },
    {
      id: 'approved_by_ops_lead',
      label: 'Approved by OPS lead',
      type: 'text',
      width: 180,
      required: false,
      editable: true,
    },
    {
      id: 'manual_case',
      label: 'Manual Case',
      type: 'status',
      width: 180,
      required: false,
      editable: true,
      options: manualCaseLSDOptions,
    },
  ],
  defaultSort: {
    columnId: 'entry_date',
    direction: 'asc', // Ascending: oldest at top, latest at bottom
  },
  permissions: {
    admin: {
      canView: true,
      canEdit: true,
      canDelete: true,
      canExport: true,
    },
    editor: {
      canView: true,
      canEdit: true,
      canDelete: false,
      canExport: true,
    },
    viewer: {
      canView: true,
      canEdit: false,
      canDelete: false,
      canExport: false,
    },
  },
};

// All available sheets
export const sheets: SheetConfig[] = [escalationSheetConfig, lsdSheetConfig];

// Helper to get sheet by ID
export const getSheetById = (id: string): SheetConfig | undefined => {
  return sheets.find((sheet) => sheet.id === id);
};
